kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: arm64

steps:
  - name: stop containers
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - cd ubuntu-server-test-apps
      - docker-compose down
  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - cd ubuntu-server-test-apps
      - docker-compose build
  - name: deploy
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      POSTGRES_DB:
        from_secret: postgres_db
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASSWORD:
        from_secret: postgres_password
      HOST:
        from_secret: host
      API_PREFIX:
        from_secret: api_prefix
    commands:
      - cd ubuntu-server-test-apps
      - docker-compose up -d
  - name: image cleanup
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker image prune -f

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - main
  event:
    - push
